name: urban-es-proposal
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - -e .
    - git+git://github.com/martibosch/swiss-uhi-utils.git@reclassify
    - git+git://github.com/woodcrafty/PyETo.git@0b7ac9f149f4c89c5b5759a875010c521aa07f0f
  - setuptools
  - wheel
  - click
  - flake8
  - flake8-isort>=4
  - pandoc
  - python-dotenv>=0.5.1
  - python=3
  - boto3  
  - ipykernel
  - descartes
  - matplotlib
  - rasterio
  - salem
  - shapely
  - scikit-image
  - swisslandstats-geopy
  - wget
